### ISSUE TITLE
Why we are using Proxy here ?

### ISSUE THREAD

**Issue by arbazkiraak** [random-robbie/google-dork#1]
Hello Robbie ,

Just want to ask , why we are using proxy = "http://127.0.0.1:8080"   Here for Dorking Result ?
we can also process without proxy , 

I'm just curious to know the reason :)

Hope you don't mind Answering !

Thanks!

**Comment by random-robbie** [comment]
it's due to loads of dorking gets a 503 so i added an option for a proxy :)

**Comment by arbazkiraak** [comment]
You Mean to avoid That Google Captcha ?

**Comment by random-robbie** [comment]
yep as if you use inurl:"&" more than like 3 times it flakes out.

**Comment by arbazkiraak** [comment]
Thanks for Sharing Info !
